In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1+arr2

array([5, 7, 9])

In [4]:
li1 = [1,2,3]
li2 = [4,5,6]

li3 = [i+j for i,j in zip(li1,li2)]
li3

# we cant add two list so we can use array

[5, 7, 9]

In [5]:
arr = np.array([1,2,3]) + 10
arr1 = np.array([1,2,3]) ** 2
arr2 = np.array([1,2,3]) ** 0.5

print(arr)
print(arr1)
print(arr2)

[11 12 13]
[1 4 9]
[1.         1.41421356 1.73205081]


In [6]:
# arange function is used for creating an array from range
arr = np.arange(100)
arr1 = np.arange(5,101,5)
arr1

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [7]:
# Matrix in Numpy
# 2D Array
arr = np.array([[1,2,3,10],[4,5,6,20],[7,8,9,30]])
print(arr[1:,1:])
print(arr[1:,1:3])
print(arr[0:2,2:4])

[[ 5  6 20]
 [ 8  9 30]]
[[5 6]
 [8 9]]
[[ 3 10]
 [ 6 20]]


In [8]:
# create multidimension array using reshape function
arr = np.arange(1,13).reshape(3,4)
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# create digonal matrix
arr = np.eye(3,dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
# create ones and zeros array
arr = np.ones((3,3),dtype='int')
arr1 = np.zeros((3,3),dtype='int')
print(arr1)
arr

[[0 0 0]
 [0 0 0]
 [0 0 0]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
arr1 = np.arange(1,7).reshape(3,2)
arr2 = np.arange(5,11).reshape(2,3)

print(arr1)
print(arr2)

arr1@arr2
arr1.dot(arr2)

[[1 2]
 [3 4]
 [5 6]]
[[ 5  6  7]
 [ 8  9 10]]


array([[21, 24, 27],
       [47, 54, 61],
       [73, 84, 95]])

In [12]:
# Define two matrices
matrix1 = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]

matrix2 = [[9, 8, 7], 
           [6, 5, 4], 
           [3, 2, 1]]

# Initialize the result matrix with zeros
result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

# Perform matrix multiplication
for i in range(len(matrix1)):  # Iterate over rows of matrix1
    for j in range(len(matrix2[0])):  # Iterate over columns of matrix2
        for k in range(len(matrix2)):  # Iterate over rows of matrix2
            result[i][j] += matrix1[i][k] * matrix2[k][j]

# Display the matrices and the result
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

print("\nResultant Matrix after Multiplication:")
for row in result:
    print(row)


Matrix 1:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Resultant Matrix after Multiplication:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [13]:
t = 1,
print(type(t))

s = {1, 2, 3}
s.add(4)
print(s)

<class 'tuple'>
{1, 2, 3, 4}


In [53]:
a = 7;b=5
print("a =",a,b,sep='00000',end='\n\n\n')
print("a =",a,sep='0', end='')


a =000007000005


a =07

In [15]:
# creating an ndarray 
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
arr1

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# change the datatype of array
arr = np.array([1,2,3,4,'w'])
arr

arr1 = np.array([1,2,3,4],complex)
arr1

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [17]:
# Finding the dimension of an array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)

2


In [18]:
# Finding the size of each array element
arr = np.array([[1,2,3,4]])
print("Each item contains",arr.itemsize,"bytes")

Each item contains 8 bytes


In [19]:
# Finding the datatype of each array item
arr = np.array([[1,2,3,4,'j']])
arr.dtype

dtype('<U21')

In [20]:
# Finding the shape and size of the array
arr = np.array([[1,2,4],[6,7,9]])
print("Shape",arr.shape)
print("The Total Element in array : ",arr.size)

Shape (2, 3)
The Total Element in array :  6


In [21]:
# Reshaping the array
arr = np.array([[1,2,3],[4,5,6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# Slicing in the array
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[0,2]

np.int64(3)

In [23]:
# Finding the Minimum,Maximum and sum of an array
arr = np.array([[1,2,3]])
print(arr.sum())
print(arr.min())
print(arr.max())

6
1
3


In [24]:
# Numpy array Axis
arr = np.array([[1,2,3],[4,0,1]])
print(arr.max(axis=0)) #axis 0 means all column wise
print(arr.min(axis=1)) #axis 1 means all row wise

[4 2 3]
[1 0]


In [25]:
# Finding square root and standard deviation
arr = np.array([[1,2,3]]) 
print(np.sqrt(arr))
np.std(arr)


[[1.         1.41421356 1.73205081]]


np.float64(0.816496580927726)

In [26]:
# Arithmetic operations on the array
arr1 = np.array([[2,4,6]])
arr2 = np.array([[1,3,5]])
print("Addition : ",arr1+arr2)
print("Substraction : ",arr1-arr2)
print("Multiplication : ",arr1*arr2)
print("Division : ",arr1/arr2)

Addition :  [[ 3  7 11]]
Substraction :  [[1 1 1]]
Multiplication :  [[ 2 12 30]]
Division :  [[2.         1.33333333 1.2       ]]


In [27]:
# Array Concatenation
arr1 = np.array([[2,4],[6,8]])
arr2 = np.array([[1,3],[5,7]])
print("Horizontal Concatination",np.hstack((arr1,arr2)))
print("Vertical Concatination",np.vstack((arr1,arr2)))

Horizontal Concatination [[2 4 1 3]
 [6 8 5 7]]
Vertical Concatination [[2 4]
 [6 8]
 [1 3]
 [5 7]]


In [28]:
# NUMPY ARRAY CREATION
# Numpy empty
arr = np.empty((3,2),dtype=int)
arr


array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
# NumPy.Zeros
arr = np.zeros((2,3),int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
# NumPy.ones
arr = np.ones((3,2),int)
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
# creating numpy array using the list
l = [1,2,3,4,5]
arr = np.asarray(l)
print(type(arr))
print(arr)

# creating a numpy array using Tuple
t = (1,2,3,4)
arr1 = np.asarray(t)
print(type(arr1))
print(arr1) 

# creating a numpy array using more than one list
l = [[1,2,3],[4,5,6]]
arr2 = np.asarray(l)
print(type(arr2))
print(arr2)


<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [32]:
# Numpy.arrange
arr = np.arange(1,10,1,int).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# Adding and Removing elements in the array

import numpy as np
arr = np.array([1,2,3,4])
print(np.append(arr,5))

print(np.insert(arr,2,8989))

np.delete(arr,1)

[1 2 3 4 5]
[   1    2 8989    3    4]


array([1, 3, 4])

In [47]:
# Sorting Searching and filtering an array
# sort array
arr = np.array([[1,9,3,6,1,5]])
# print(np.sort(arr))

# search array
print(np.where(arr==5))

(array([0]), array([5]))


In [35]:
# Numpy Broadcasting
import numpy as np
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b = np.array([2,4,6,8])
print("\nprinting array a..")
print(a)
print("\nprinting array b..")
print(b)
print("\nAdding arrays a and b ..")
c = a + b;
print(c)


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [36]:
# # Numpy Array Iteration
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(arr):
    print(i,end=" ")

# Transpose of a Matrix
arr.T    

1 2 3 4 5 6 7 8 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
# Array Values Modification
# arr = np.array([[1,2,3,4]]) * 3
arr

for i in np.nditer(arr):
    print(i*3,end=" ")

3 6 9 12 15 18 21 24 

In [38]:
# Numpy Bitwise Operators
a = 10 
b = 12
print(bin(a))
print(bin(b))
print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))
print(np.bitwise_not(a))
print(np.bitwise_not(b))

0b1010
0b1100
8
14
-11
-13


In [39]:
# Rounding Functions
arr = np.array([12.202, 90.23120, 123.020, 23.202])
print("printing the original array values:",end = " ")
print(arr)
print("Array values rounded off to 2 decimal position",np.around(arr, 2))
print("Array values rounded off to -1 decimal position",np.around(arr, -1))

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [40]:
# The numpy.floor() function
import numpy as np
arr = np.array([12.202, 90.23120, 123.020, 23.202])
print(np.floor(arr))

[ 12.  90. 123.  23.]


In [41]:
# The numpy.ceil() function
import numpy as np
arr = np.array([12.202, 90.23120, 123.020, 23.202])
print(np.ceil(arr))

[ 13.  91. 124.  24.]


In [42]:
# numpy.nonzero() function
import numpy as np
b = np.array([12, 90, 380, 12, 211])
print("printing original array",b)
print("printing location of the non-zero elements")
print(b.nonzero())

printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4]),)


In [43]:
# numpy.where() function
import numpy as np
b = np.array([12, 90, 380, 12, 211])
print(np.where(b>12))
c = np.array([[20, 24],[21, 23]])
print(np.where(c>20))

(array([1, 2, 4]),)
(array([0, 1, 1]), array([1, 0, 1]))


In [44]:
# Numpy Copies And Views
print("Copies")
import numpy as np
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])
print("Original Array:\n",a)
print("\nID of array a:",id(a))
b = a
print("\nmaking copy of the array a")
print("\nID of b:",id(b))
b.shape = 4,3;
print("\nChanges on b also reflect to a:")
print(a)

print("\nView Method")
import numpy as np
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])
print("Original Array:\n",a)
print("\nID of array a:",id(a))
b = a.view()
print("\nID of b:",id(b))
print("\nprinting the view b")
print(b)
b.shape = 4,3;
print("\nChanges made to the view b do not reflect a")
print("\nOriginal array \n",a)
print("\nview\n",b)

Copies
Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2294912769872

making copy of the array a

ID of b: 2294912769872

Changes on b also reflect to a:
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]

View Method
Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2294912768336

ID of b: 2294912767760

printing the view b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the view b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

view
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [45]:
# Numpy Matrix
a = np.array([[1,2],[2,3]])
b = np.array([[2,3],[5,1]])
print(np.dot(a,b))

[[12  5]
 [19  9]]
