In [1]:
# Creating an Array

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [2]:
# Create Multidimensional Array 
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,2,3,4,5]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11  2  3  4  5]]


In [3]:
# to Change the Data Type of array
import numpy as np
arr = np.array([1,2,3,4,5,"Jameel"])
arr1 = np.array([1,2,3,4,5],float)
print(arr)
print(arr1)
print(type(arr1))

['1' '2' '3' '4' '5' 'Jameel']
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [4]:
# Finding the size of Each Element in an Array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.itemsize,"bytes")


8 bytes


In [5]:
# Finding the data type of each Array item
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [6]:
# Finding the shape and size of the array
import numpy as ap
arr = np.array([[8,3,2,56,3]])
print(arr.shape)

(1, 5)


In [7]:
# Reshaping the array objects
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
print("Original Array : ", arr)
print("Reshaping Array : ", arr.reshape(2,3))

Original Array :  [[1 2]
 [3 4]
 [5 6]]
Reshaping Array :  [[1 2 3]
 [4 5 6]]


In [8]:
# Slicing in the Array
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1,0:2])
print(arr[2,3])

[5 6]
12


In [9]:
import numpy as np
arr = np.array([[1,2,3,4]])
print(arr.max())
print(arr.min())
print(arr.sum())

4
1
10


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[7,8,9],[10,11,12]])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
# Another Syntax of creating an array

import numpy as np 
a = [10,20,3,0,]
arr = np.array(a)
print(arr)

[10 20  3  0]


In [12]:
# Finding the  length of element

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(len(arr)) #find the total array in array  
print(len(arr)) #find the total element of an array 

2
2


In [13]:
# Mathematical Operation on array

arr1 = np.array([[10,20,30,40]])
arr2 = np.array([[40,30,50,40]])

# addition
print(arr1+arr2)
print(np.add(arr1,arr2))

# Substraction
print(arr1-arr2)
print(np.subtract(arr1,arr2))

# Multiplication
print(arr1*arr2)
print(np.multiply(arr1,arr2))

# Division
print(arr1/arr2)
arr3 = np.divide(arr1,arr2)
print(np.astype(arr3,int))

a = np.array([[2,3,4,5]])
b = np.array([[2]])
print(np.pow(a,b)) #Power
print(np.sqrt([4,9,12,24])) #Square Root


[[50 50 80 80]]
[[50 50 80 80]]
[[-30 -10 -20   0]]
[[-30 -10 -20   0]]
[[ 400  600 1500 1600]]
[[ 400  600 1500 1600]]
[[0.25       0.66666667 0.6        1.        ]]
[[0 0 0 1]]
[[ 4  9 16 25]]
[2.         3.         3.46410162 4.89897949]


In [14]:
# Combining and spliting array

# Concatenate
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[4,5,8]])

print(np.concatenate([a,b]))
print(np.hstack([a,b]))
print(np.vstack([a,b]))

# Spliting
c = np.array([1,2,3,4,5])
d = np.array_split(c,3)
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 8]]
[[1 2 3 7 8 9]
 [4 5 6 4 5 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 8]]
[array([1, 2]), array([3, 4]), array([5])]


In [15]:
# Adding and Removing Element in Array

# append - add the element in the last position of an array

arr = np.array([1,2,3,4,5])
print(np.append(arr,[90,100,110]))

# insert - insert an element on the specific location

print(np.insert(arr,2,900))

# Delete 

print(np.delete(arr,2))
print(np.append(arr,[10,50,90]))


[  1   2   3   4   5  90 100 110]
[  1   2 900   3   4   5]
[1 2 4 5]
[ 1  2  3  4  5 10 50 90]


In [16]:
import numpy as np 
a = np.array([[1,2],[5,6],[9,10]])
b = np.array([[11,12],[13,14],[15,16]]) 

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[ 1  2 11 12]
 [ 5  6 13 14]
 [ 9 10 15 16]]


In [17]:
import numpy as np
arr = np.array([[1,2,3,5],[6,7,8,9]])
print(len(arr))
print(arr.size)
print(arr.astype(float))

2
8
[[1. 2. 3. 5.]
 [6. 7. 8. 9.]]


In [18]:
# Search in array
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.searchsorted(arr,3))


2


In [19]:
# Sort array
import numpy as np 
arr = np.array([1,9,4,7,27,3,2])
print(np.sort(arr))

[ 1  2  3  4  7  9 27]


In [20]:
# Filter array
import numpy as np 
arr = np.array([2,3,1,3,1,2])
# fa = [True,False,True,False]
fa = arr>2
new = arr[fa]
new

array([3, 3])

In [21]:
# Aggregation Function in Numpy

import numpy as np 

arr = np.array([[10,4,2,7,7]])
print(arr.sum())
print(arr.max())
print(arr.min())
print(np.size(arr))
print(len(arr))
print(np.mean(arr))
print(np.median(arr))
# print(np.mod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

30
10
2
5
1
6.0
7.0
[10 14 16 23 30]
[  10   40   80  560 3920]
