np.sort

Return a Sort of function

In [9]:
import numpy as np 
# 1d array
a = np.random.randint(1,100,15)
np.sort(a)

array([ 1,  4,  7, 10, 16, 17, 19, 26, 28, 40, 48, 69, 71, 74, 83],
      dtype=int32)

In [10]:
# 2d array
b = np.random.randint(1,100,24).reshape(6,4)
# axis = 0 column wise sorting
# axis = 1 rows wise sorting 
np.sort(b,axis=0)

np.sort(b)[::-1]

array([[15, 52, 63, 70],
       [ 4, 25, 51, 95],
       [ 1, 58, 68, 91],
       [26, 27, 37, 89],
       [22, 26, 56, 66],
       [36, 43, 80, 96]], dtype=int32)

np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [11]:
np.append(a,200)

# add new column using append in 2d array

np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[36., 96., 80., 43.,  1.],
       [26., 56., 66., 22.,  1.],
       [37., 89., 27., 26.,  1.],
       [58., 68., 91.,  1.,  1.],
       [51.,  4., 25., 95.,  1.],
       [52., 15., 70., 63.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)
print(np.concatenate((c,d),axis=0))
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

with the help of the unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [13]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.extend_dims

with the help of Numpy.extend_dims() method, we can get the expended the dimensions of an array

using this we can easily convert 1d array to 2d array

In [14]:
np.expand_dims(a,axis=0).shape
np.expand_dims(a,axis=1)

array([[28],
       [26],
       [17],
       [19],
       [ 7],
       [ 1],
       [16],
       [40],
       [74],
       [69],
       [71],
       [83],
       [10],
       [48],
       [ 4]], dtype=int32)

np.where

The numpy.where() function returns the indices of element in an input array where the given condition is satisfied

In [15]:
f = np.array([30,12,42,35,10])
# find all values greater than 20
np.where(f > 20)

# replace all values greater than 20 with 0
np.where(f>20,0,f)

array([ 0, 12,  0,  0, 10])

np.argmax()

The numpy.argmax() function return indices of the max element of the array in a particular axis.
iska use maximum number ka index find krne k liye kiya jata h

In [16]:
print(b)
np.argmax(b, axis=1)

[[36 96 80 43]
 [26 56 66 22]
 [37 89 27 26]
 [58 68 91  1]
 [51  4 25 95]
 [52 15 70 63]]


array([1, 2, 1, 2, 3, 2])

In [17]:
# np.argmin
print(a)
np.argmin(a)

[28 26 17 19  7  1 16 40 74 69 71 83 10 48  4]


np.int64(5)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [18]:
import numpy as np
g = np.arange(1,8)
print(g.cumsum()) #1+2+3+4+5+6+7=28
print(g.cumprod()) #1*2*3*4*5*6*7=5040

[ 1  3  6 10 15 21 28]
[   1    2    6   24  120  720 5040]


np.percentile

np.percentile() functionused to compute nth percentile of the given data(array element) along the specified axis.

In [21]:
print(a)
np.percentile(a,50)

[28 26 17 19  7  1 16 40 74 69 71 83 10 48  4]


np.float64(26.0)

np.histogram

Numpy has a buit-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [23]:
print(a)
np.histogram(a,bins=([0,50,100]))

[28 26 17 19  7  1 16 40 74 69 71 83 10 48  4]


(array([11,  4]), array([  0,  50, 100]))

np.isin

iska use ek array m multiple elements ko search krne k liye kiya jata h 

In [24]:
a

array([28, 26, 17, 19,  7,  1, 16, 40, 74, 69, 71, 83, 10, 48,  4],
      dtype=int32)

In [25]:
ele = [17,20,25,40,10,1,55]
a[np.isin(a,ele)]

array([17,  1, 40, 10], dtype=int32)

np.flip

iska use array ko flip krne k liye kiyta jata h 

In [26]:
h = np.array([1,5,2,73,9])
np.flip(h)

array([ 9, 73,  2,  5,  1])

np.put

iska use array m available elements ko change krne k liye kiya jata h. ye original array m change krta h

In [30]:
print(h)
np.put(h,[0,1],[10,20])
print(h)


[10 20  2 73  9]
[10 20  2 73  9]


np.delete


In [34]:
print(np.delete(h,[1,3,4]))
h

[10  2]


array([10, 20,  2, 73,  9])

Set Function

    1. np.union1d
    2. np.intersect1d
    3. np.setdiffd
    4. np.setxor1d
    5. np.in1d

In [40]:
i = np.array([1,2,3,4,5,6])
j = np.array([3,4,5,6,7,8])

print(np.union1d(i,j))
print(np.intersect1d(i,j))
print(np.setdiff1d(i,j))
print(np.setxor1d(i,j))
print(np.in1d(i,j))

[1 2 3 4 5 6 7 8]
[3 4 5 6]
[1 2]
[1 2 7 8]
[False False  True  True  True  True]


C:\Users\Jameel Ahmed\AppData\Local\Temp\ipykernel_21044\3103693035.py:8: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(i,j))
